  version: '3.9'


  services:
    postgres:
      image: postgres:14.10
      restart: unless-stopped
      container_name: postgres-container
      environment:
        POSTGRES_DB: gobus
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345
      ports:
        - "5434:5432"
      networks:
        - app-network

    redis:
      image: redis:6.0.16
      restart: unless-stopped
      container_name: redis-container
      ports:
        - "5000:6379"
      networks:
        - app-network

    go-bus:
      image: aswinmanoj/go-bus-reservation:latest
      container_name: go-bus-container
      restart: unless-stopped
      ports:
        - "8080:8080"
      depends_on:
        - postgres
        - redis
      networks:
        - app-network

  networks:
    app-network:
      driver: bridge
